return {
    {{"Legitbot"}, {"Ragebot"}, {"Visuals"}, {"Misc"}, {"Settings"}},
    {{"Master Switch"}, {"Master Switch"}, {"Master Switch"}, {"Master Switch"}},
    {
        {"Aimbot"},
        {"Triggerbot"},
        {"Weapon"},
        {"Other"},
        {"Semirage"},
        {"Aimbot"},
        {"Accuracy"},
        {"Targeting"},
        {"Anti-Aim"},
        {"Overlay"},
        {"Local"},
        {"World"},
        {"Chams"},
        {"Other"},
        {"General"},
        {"Movement"},
        {"Enhancement"},
        {"Configurations"},
        {"Lua Scripts"},
        {"Theme"},
        {"Advanced"}
    },
    {
        {"Toggle"},
        {"Weapon"},
        {"Target"},
        {"Hitbox Selection"},
        {"Toggle"},
        {"Weapon"},
        {"Target"},
        {"Hitbox Scan"},
        {"Aiming"},
        {"Visibility"},
        {"Accuracy"},
        {"Target"},
        {"Extra"},
        {"Aimbot"},
        {"Toggle"},
        {"Automation"},
        {"Target"},
        {"Accuracy"},
        {"Position Adjustment"},
        {"Hitbox Points"},
        {"Mode"},
        {"Anti-Aim"},
        {"Condition"},
        {"Advanced"},
        {"Player"},
        {"World"},
        {"Camera"},
        {"Materials"},
        {"Selection"},
        {"Model"},
        {"Attachments"},
        {"Model"},
        {"Attachments"},
        {"Model"},
        {"Viewmodel"},
        {"Attachments"},
        {"Extra"},
        {"Effects"},
        {"Extra"},
        {"Restrictions"},
        {"Bypass"},
        {"Jump"},
        {"Strafe"},
        {"Fakelag"},
        {"Fake Latency"},
        {"Exploits"},
        {"Appearance"},
        {"Browse"},
        {"File"},
        {"Configuration"},
        {"Other"},        
        {"Browse"},
        {"File"},
        {"Script"},
        {"Other"},
        {"Window Header"},
        {"Navigation"},
        {"Window Footer"},
        {"UI"},
        {"Tab List"},
        {"UI"},
        {"General"},
        {"Lua Security"}
    },
    {
        {"Enable", "Enables legit aimbot"},
        {"Aim Key", "Set the aimbot on key"},
        {"Auto Fire", "Fires without pressing any key"},
        {"Fire On Press", "Fires when pressing the aimbot key"},
        {"Auto Pistol Interval", "Interval between shots for automatic mode"},
        {"Filter", "Set the aimbot target filter"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Enable", "Enables triggerbot"},
        {"Trigger Key", "Activate trlggerbot on key press"},
        {"Auto Fire", "Let triggerbot fire without pressing any key"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Filter","Set the triggerbot target filter"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Backtrack Time","How many positions in the past are allowed"},
        {"Silent Aimbot","Autoaim when in Low FOV range"},
        {"Enable","Enables rage aimbot"},
        {"Aim Key","Set the aimbot on key"},
        {"Auto Pistol","Makes pistols fire like automatic weapons"},
        {"Filter","Set the aimbot target filter"},
        {"FOV","Maximum field of view the aimbot will target within"},
        {"Aim Lock","lncrease priority of latest target"},
        {"Friendly Fire","Target teammates when aimbotting"},
        {"Silent Aim",{"Off","Client-Sided","Server-Sided","Suppress view movement when aimbotting"}},
        {"Anti-Recoil","Counter weapon recoil for higher accuracy"},
        {"Anti-Spread","Counter weapon spread for higher accuracy"},
        {"Backtracking","Aim at enemy history positions"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Shared"},
        {"Pistol"},
        {"Sub Machine Gun"},
        {"Rifle"},
        {"Shotgun"},
        {"Sniper"},
        {"Pitch",{"Off","Emotion","Down","Fake Down",""}},
        {"Yaw",{"Off","Backward","Sideways Left","Sideways Right","Spinbot","Jitter Backward","Jitter Forward","Jitter Sideways",""}},
        {"Disable on Melee"},
        {"Disable on Use"},
        {"Disable on Ladder"},
        {"Jitter Range","Maximum allowed yaw variance"},
        {"Spinbot Speed","Maximum speed of spinbot"},
        {"Filter"},
        {"Box", {"Off", "Outlined", "Normal", "Draw 2D box around entity"}},
        {"Box Precision","Match 2D box with model bounds"},
        {"Name","Draw entity name"},
        {"Skeleton","Draw entity skeleton"},
        {"Health"},
        {"Weapon", {"Off", "Show Active", "Show All", ""}},
        {"Filter"},
        {"Box", {"Off", "Outlined", "Normal", "Draw 2D box around entity"}},
        {"Name","Draw entity name"},
        {"Third Person Enable","Enable third person view"},
        {"Third Person Distance","Distance of the camera"},
        {"Walls Color"},
        {"Static Props Color"},
        {"Skybox","Change how the sky looks"},
        {"Occluded",{"Off", "Flat", "Color","Material occluded by walls"}},
        {"Visible",{"Off", "Flat", "Color","Visible material"}},
        {"Occluded",{"Off", "Flat", "Color","Material occluded by walls"}},
        {"Visible",{"Off", "Flat", "Color","Visible material"}},
        {"Occluded",{"Off", "Flat", "Color","Material occluded by walls"}},
        {"Visible",{"Off", "Flat", "Color","Visible material"}},
        {"Occluded",{"Off", "Flat", "Color","Material occluded by walls"}},
        {"Visible",{"Off", "Flat", "Color","Visible material"}},
        {"Occluded",{"Off", "Flat", "Color","Material occluded by walls"}},
        {"Visible",{"Off", "Flat", "Color","Visible material"}},
        {"Occluded",{"Off", "Flat", "Color","Material occluded by walls"}},
        {"Visible",{"Off", "Flat", "Color","Visible material"}},
        {"Occluded",{"Off", "Flat", "Color","Material occluded by walls"}},
        {"Visible",{"Off", "Flat", "Color","Visible material"}},
        {"Radar","Display custom radar"},
        {"Radar Range","Set radar range"},
        {"Radar Transparency","Set radar transpareny"},
        {"Overlay Range"},
        {"Crosshair","Display custom crosshair"},
        {"Crosshair Recoil", {"Off", "Line", "Fade", "Draws the spot where your shots will go"}},
        {"Anti-OBS","Hide visuals from screen recorder"},
        {"Anti-Screenshot","Hide visuals from screenshots"},
        {"No Recoil"},
        {"No Sky"},
        {"Show Spectators","See who is spectating you"},
        {"Anti-SMAC","Avoid Source Mod Anti-Cheat detections"},
        {"Bypass sv_pure", "Allow custom models and materials from game directory."},
        {"Bypass sv_cheats","Bypass protected convars"},
        {"Bypass client-side","Bypass client-side protection"},
        {"Unlock Steam Achievements"},
        {"Show hidden ConVars"},
        {"Auto Jump","Allow for continuous jumping"},
        {"Edge Jump","Jump right before falling of an edge"},
        {"Duck Jump","Reach higher by crouching while jumpin"},
        {"Enable","Enable autostrafer to gain more speed"},
        {"Air Strafe","Increases forward speed while jumping"},
        {"Ground Strafe","lncreases forward speed while walking"},
        {"Strafe Mode", {"Silent", "Normal", "Sideways", "W-Only", "Mouse", "Select style of autostrafing"}},
        {"Circle Strafe","Strafe in circles when pressing a key"},
        {"Snake Strafe","Strafe like a snake when pressing a key"},
        {"Retrack Speed","Autostrafe in direction of pressed movement keys"},
        {"WASD-Movement","Autostrafe in direction of pressed movement keys"},
        {"Enable","Enable lag effect"},
        {"On Key","Enable lag only when holding this key"},
        {"Type", {"Factor", "Switch", "Adaptive", "Random", 'Type or "pattern" of lag'}},
        {"Factor","How many commands will be choked"},
        {"Enable"},
        {"On Key"},
        {"Amount"},
        {"Lag Exploit","Activate lag exploit functionality"},
        {"Lag Exploit Cmds","Number of commands to use during lag"},
        {"Air Stuck","Freeze yourself in mid air"},
        {"Steal Name",{"Off", "Team Only","Enemy Only", "Steal other player names"}},
        {"Steal Interval","lnterval between name changes"},
        {"Chat Spam","Advertise AIMWARE in chat"},
        {"Chat spam Interval","Interval between chat spam"},
        {"Name", "Create or rename configuration"},
        {"Create"},
        {"Rename"},
        {"Load"},
        {"Save"},
        {"Reset"},
        {"Delete"},
        {"Import From Clipboard"},
        {"Export To Clipboard"},
        {"Set As Default"},
        {"Refresh List"},
        {"Name", "Create or rename script"},
        {"Create"},
        {"Rename"},
        {"Unload"},
        {"Load"},
        {"Load With Configurations"},
        {"Edit"},
        {"Delete"},
        {"Reset Lua State"},
        {"Set As Autorun"},
        {"Refresh List"},
        {"Background"},
        {"Line"},
        {"Text"},
        {"Background"},
        {"Active"},
        {"Active Shadow"},
        {"Text"},
        {"Background"},
        {"Text"},
        {"Background #1"},
        {"Background #2"},
        {"Border"},
        {"Text"},
        {"Text Active"},
        {"Active Shadow"},
        {"Tab Active Decorator"},
        {"Tab Active Background"},
        {"Dpi Scale", {"75%", "100% (default)", "125%", "150%", "175%", "200%", "225%", "250%", "275%", "300%", "Scale the UI size by this amount."}},
        {"Show Binds", {"Off", "Vars", "Names", "Short Names", "Show the list of current binds and their current value."}},
        {"Show Confirmations", "Ask for confirmation when saving settings."},
        {"菜单语言", "仅限CSS中修改,其他游戏切勿使用"},
        {"Open Menu Key", "Bind for main menu toggle."},
        {"Open Console Key", "Console for more customization."},
        {"Open Settings Folder"},
        {"Allow scripts editing lua files"},
        {"Allow scripts editing cfg files"},
        {"Allow internet connections from scripts", "⚠ This can leak your IP address or perform DoS attacks."},
        {"Allow game specific scripting (e.g. Panorama JS)", "⚠ This can be used for malicious code with Steam API."},
        {"Allow insecure FFI library for extended API", "⚠ This is abusable far inalwares, run only trusted scripts."},
        {"Save Lua Permissions"}
    },
    {
        {"Hitbox Advance Multipler","How fast aimbot should switch to the next hitbox"},
        {"Nearest To Crosshair","Priority hitbox nearest to crosshair as first"},
        {"Hitbox Advance Multipler","How fast aimbot should switch to the next hitbox"},
        {"Nearest To Crosshair","Priority hitbox nearest to crosshair as first"},
        {"Hitbox Advance Multipler","How fast aimbot should switch to the next hitbox"},
        {"Nearest To Crosshair","Priority hitbox nearest to crosshair as first"},
        {"Hitbox Advance Multipler","How fast aimbot should switch to the next hitbox"},
        {"Nearest To Crosshair","Priority hitbox nearest to crosshair as first"},
        {"Hitbox Advance Multipler","How fast aimbot should switch to the next hitbox"},
        {"Nearest To Crosshair","Priority hitbox nearest to crosshair as first"},
        {"Hitbox Advance Multipler","How fast aimbot should switch to the next hitbox"},
        {"Nearest To Crosshair","Priority hitbox nearest to crosshair as first"},
        {"Trigger Delay","Delay shot after trigger lock"},
        {"Trigger Burst","Keep firing after trigger lock"},
        {"Anti-Recoil","Account for recoil when trigger scanning"},
        {"Trigger Delay","Delay shot after trigger lock"},
        {"Trigger Burst","Keep firing after trigger lock"},
        {"Anti-Recoil","Account for recoil when trigger scanning"},
        {"Trigger Delay","Delay shot after trigger lock"},
        {"Trigger Burst","Keep firing after trigger lock"},
        {"Anti-Recoil","Account for recoil when trigger scanning"},
        {"Trigger Delay","Delay shot after trigger lock"},
        {"Trigger Burst","Keep firing after trigger lock"},
        {"Anti-Recoil","Account for recoil when trigger scanning"},
        {"Trigger Delay","Delay shot after trigger lock"},
        {"Trigger Burst","Keep firing after trigger lock"},
        {"Anti-Recoil","Account for recoil when trigger scanning"},
        {"Trigger Delay","Delay shot after trigger lock"},
        {"Trigger Burst","Keep firing after trigger lock"},
        {"Anti-Recoil","Account for recoil when trigger scanning"},
        {"Smooth Factor","Smooth out aimbot movement"},
        {"Smooth Method","Method to use for smooth movement"},
        {"Randomize Factor","Randomize aimbot target position"},
        {"Curve Factor","How non-linear the movement will be"},
        {"Smooth Factor","Smooth out aimbot movement"},
        {"Smooth Method","Method to use for smooth movement"},
        {"Randomize Factor","Randomize aimbot target position"},
        {"Curve Factor","How non-linear the movement will be"},
        {"Smooth Factor","Smooth out aimbot movement"},
        {"Smooth Method","Method to use for smooth movement"},
        {"Randomize Factor","Randomize aimbot target position"},
        {"Curve Factor","How non-linear the movement will be"},
        {"Smooth Factor","Smooth out aimbot movement"},
        {"Smooth Method","Method to use for smooth movement"},
        {"Randomize Factor","Randomize aimbot target position"},
        {"Curve Factor","How non-linear the movement will be"},
        {"Smooth Factor","Smooth out aimbot movement"},
        {"Smooth Method","Method to use for smooth movement"},
        {"Randomize Factor","Randomize aimbot target position"},
        {"Curve Factor","How non-linear the movement will be"},
        {"Smooth Factor","Smooth out aimbot movement"},
        {"Smooth Method","Method to use for smooth movement"},
        {"Randomize Factor","Randomize aimbot target position"},
        {"Curve Factor","How non-linear the movement will be"},
        {"Auto Wall","Fire through penetrable walls"},
        {"Auto Wall","Fire through penetrable walls"},
        {"Auto Wall","Fire through penetrable walls"},
        {"Auto Wall","Fire through penetrable walls"},
        {"Auto Wall","Fire through penetrable walls"},
        {"Auto Wall","Fire through penetrable walls"},
        {"Recoil Control System","Smoothly counter weapon recoil"},
        {"Standalone Recoil Control","Enable RCS while aiming freely"},
        {"Horizontal Recoil","How much of horizontal recoil will be countered"},
        {"Vertical Recoil","How much of vertical recoil will be countered"},
        {"Recoil Control System","Smoothly counter weapon recoil"},
        {"Standalone Recoil Control","Enable RCS while aiming freely"},
        {"Horizontal Recoil","How much of horizontal recoil will be countered"},
        {"Vertical Recoil","How much of vertical recoil will be countered"},
        {"Recoil Control System","Smoothly counter weapon recoil"},
        {"Standalone Recoil Control","Enable RCS while aiming freely"},
        {"Horizontal Recoil","How much of horizontal recoil will be countered"},
        {"Vertical Recoil","How much of vertical recoil will be countered"},
        {"Recoil Control System","Smoothly counter weapon recoil"},
        {"Standalone Recoil Control","Enable RCS while aiming freely"},
        {"Horizontal Recoil","How much of horizontal recoil will be countered"},
        {"Vertical Recoil","How much of vertical recoil will be countered"},
        {"Recoil Control System","Smoothly counter weapon recoil"},
        {"Standalone Recoil Control","Enable RCS while aiming freely"},
        {"Horizontal Recoil","How much of horizontal recoil will be countered"},
        {"Vertical Recoil","How much of vertical recoil will be countered"},
        {"Recoil Control System","Smoothly counter weapon recoil"},
        {"Standalone Recoil Control","Enable RCS while aiming freely"},
        {"Horizontal Recoil","How much of horizontal recoil will be countered"},
        {"Vertical Recoil","How much of vertical recoil will be countered"},
        {"Minimum FOV Range","Minimum field of view for aim lock"},
        {"Maximum FOV Range","Maximum field of view for aim lock"},
        {"Target Switch Delay","Time aimbot will wait before switching target"},
        {"First Shot Delay","Time till aimbot fires first shot"},
        {"Minimum FOV Range","Minimum field of view for aim lock"},
        {"Maximum FOV Range","Maximum field of view for aim lock"},
        {"Target Switch Delay","Time aimbot will wait before switching target"},
        {"First Shot Delay","Time till aimbot fires first shot"},
        {"Minimum FOV Range","Minimum field of view for aim lock"},
        {"Maximum FOV Range","Maximum field of view for aim lock"},
        {"Target Switch Delay","Time aimbot will wait before switching target"},
        {"First Shot Delay","Time till aimbot fires first shot"},
        {"Minimum FOV Range","Minimum field of view for aim lock"},
        {"Maximum FOV Range","Maximum field of view for aim lock"},
        {"Target Switch Delay","Time aimbot will wait before switching target"},
        {"First Shot Delay","Time till aimbot fires first shot"},
        {"Minimum FOV Range","Minimum field of view for aim lock"},
        {"Maximum FOV Range","Maximum field of view for aim lock"},
        {"Target Switch Delay","Time aimbot will wait before switching target"},
        {"First Shot Delay","Time till aimbot fires first shot"},
        {"Minimum FOV Range","Minimum field of view for aim lock"},
        {"Maximum FOV Range","Maximum field of view for aim lock"},
        {"Target Switch Delay","Time aimbot will wait before switching target"},
        {"First Shot Delay","Time till aimbot fires first shot"},
        {"Auto Wall","Shoot through penetrable walls"},
        {"Minimum Damage"},
        {"Auto Wall","Shoot through penetrable walls"},
        {"Minimum Damage"},
        {"Auto Wall","Shoot through penetrable walls"},
        {"Minimum Damage"},
        {"Auto Wall","Shoot through penetrable walls"},
        {"Minimum Damage"},
        {"Auto Wall","Shoot through penetrable walls"},
        {"Minimum Damage"},
        {"Auto Wall","Shoot through penetrable walls"},
        {"Minimum Damage"},
        {"Enemy"},
        {"Friendly"},
        {"Bar"},
        {"Number"},
        {"Weapon"},
    },
}
